// <auto-generated />
namespace Blue_Ribbon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AzureLaunch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AzureLaunch));
        
        string IMigrationMetadata.Id
        {
            get { return "201512020535051_AzureLaunch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
